package org.technozor.jzon.internal.processor;

/**
 * Created by slim on 4/24/14.
 */
public interface JzonConstants {
    public static final String MAPPER_CLASS_SUFFIX = "JzonGeneratedClass";
    public static final String GENERATED_BY_JZON = "GENERATED BY JZON";
}
